
import { Percent, Beef, Drumstick, ChefHat, Fish, ScrollText, DollarSign, Utensils, Flame, PiggyBank, Dumbbell, Zap, Box, UserPlus, IceCream, Soup, Droplet, Cookie, Salad } from 'lucide-react';
import { HalalIcon } from './components/HalalIcon';
import { AppConfig, PlannerConfig, Product } from './types';

// --- LOGIC CONTROL CENTER DEFAULTS ---
export const DEFAULT_APP_CONFIGS: AppConfig[] = [
    { 
        key: 'tax_exempt_food', 
        label: 'Exemption Taxes Alimentaires', 
        description: 'Si actif, aucune taxe n\'est appliquée sur les produits de catégorie alimentaire.', 
        isActive: true, 
        category: 'financial' 
    },
    { 
        key: 'display_3_decimals', 
        label: 'Format Monétaire Précis', 
        description: 'Afficher 3 décimales (ex: 0.045$) pour les coûts unitaires.', 
        isActive: false, 
        category: 'display' 
    },
    { 
        key: 'stock_alert_strict', 
        label: 'Alerte Stock Stricte', 
        description: 'Déclencher une alerte rouge immédiate si le stock calculé est ≤ 0.', 
        isActive: true, 
        category: 'inventory' 
    },
    { 
        key: 'dual_unit_display', 
        label: 'Double Unité (Lbs + Kg)', 
        description: 'Afficher simultanément le poids en Livres et en Kilogrammes.', 
        isActive: true, 
        category: 'display' 
    },
    { 
        key: 'auto_recalc_portion', 
        label: 'Recalcul Portion Auto', 
        description: 'Mettre à jour le coût portion immédiatement si le prix d\'un ingrédient change.', 
        isActive: true, 
        category: 'financial' 
    },
    { 
        key: 'prevent_zero_cost_save', 
        label: 'Validation Prix', 
        description: 'Interdire la sauvegarde ou l\'ajout au panier d\'un produit à 0.00$.', 
        isActive: true, 
        category: 'system' 
    },
    { 
        key: 'auto_loss_calculation', 
        label: 'Calcul de Perte Auto', 
        description: 'Appliquer automatiquement un % de perte standard aux produits bruts.', 
        isActive: false, 
        category: 'financial' 
    },
    { 
        key: 'show_supplier_ref', 
        label: 'Afficher Réf. Fournisseur', 
        description: 'Montrer le code fournisseur dans les listes de produits.', 
        isActive: false, 
        category: 'display' 
    },
    { 
        key: 'enforce_fr_lang', 
        label: 'Forcer Langue FR', 
        description: 'Empêcher l\'utilisation de termes anglais dans les noms de produits.', 
        isActive: false, 
        category: 'system' 
    },
    { 
        key: 'strict_inventory_lock', 
        label: 'Verrouillage Inventaire', 
        description: 'Empêcher la modification des produits si une commande est en cours.', 
        isActive: false, 
        category: 'inventory' 
    }
];

export const DEFAULT_PLANNER_CONFIG: PlannerConfig = {
    id: 'v1.0.0',
    name: 'Factory Default',
    status: 'live',
    timestamp: new Date().toISOString(),
    budget: { weeklyCap: 250, maxPricePerKg: 35 },
    custody: { childFactor: 0.5, teenFactor: 0.85 },
    essentials: { maxItems: 5, excludePremium: true },
    vip: { premiumTarget: 104, sortingWeight: 2.0 },
    condo: { overflowThreshold: 1.0, packDensity: 25 },
    variety: { maxRedMeatPercentage: 0.40, minFishPercentage: 0.15, diversityPenaltyWeight: 5, forceVarietyInjection: true },
    timeZoneProtocol: {
        storageStandard: 'UTC',
        contextVariable: 'User_IANA_TimeZone',
        evaluationScope: 'Local_Wall_Clock_Time'
    }
};

// --- AMQ KNOWLEDGE BASE (From PDF Report 2025) ---
export const AMQ_KNOWLEDGE_BASE = {
    // Page 3: Profils de Consommation
    profiles: [
        {
            id: 'single',
            label: 'Personne Seule',
            proteinPerSupper: 125, 
            description: "Congélateur domestique suffisant.",
            recommendedFreq: 1, 
            icon: 'User'
        },
        {
            id: 'couple',
            label: 'Couple',
            proteinPerSupper: 250, 
            description: "Commandes bimensuelles ou annuelles recommandées.",
            recommendedFreq: 2,
            icon: 'Users'
        },
        {
            id: 'family_small',
            label: 'Famille (2 enfants <12)',
            proteinPerSupper: 450, 
            description: "Optimisation budget et gaspillage (-48%).",
            recommendedFreq: 4,
            icon: 'Baby'
        },
        {
            id: 'family_teens',
            label: 'Famille (2 ados)',
            proteinPerSupper: 600, 
            description: "Volume élevé, nécessite congélateur coffre.",
            recommendedFreq: 4,
            icon: 'UserPlus'
        }
    ],
    // Page 6: Espace Congélateur
    freezerLogic: {
        lbsPerCubicFoot: 25, // 1 pi3 = 25 lbs
        fridgeFreezerCapacity: 3.5, // 3.5 pi3 standard fridge freezer
        chestRecommendedFamily: 7, // 7-10 pi3 recommended for family
    },
    // Page 5: Savings
    financials: {
        annualSavingsMin: 0.12, // 12%
        annualSavingsMax: 0.32, // 32%
        wasteReduction: 0.48 // 48%
    },
    // Page 4: Halal Trends
    halal: {
        growth: 0.18, // +18% demand
        avgStorage: 11.5 // 9-14 cu ft avg
    }
};

export const CATEGORIES = [
  { id: 'Rabais', label: 'En Rabais', icon: Percent },
  { id: 'Halal', label: 'Halal', icon: HalalIcon },
  { id: 'Boeuf', label: 'Bœuf', icon: Beef },
  { id: 'Poulet', label: 'Poulet', icon: Drumstick },
  { id: 'Porc', label: 'Porc', icon: ChefHat },
  { id: 'Poisson/Fruits de mer', label: 'Poissons & Mer', icon: Fish },
  { id: 'Gibier & Autres', label: 'Gibier & Autres', icon: ScrollText },
  { id: 'Prêt-à-manger', label: 'Prêt-à-manger', icon: DollarSign },
  { id: 'Entrée', label: 'Entrées', icon: Salad },
  { id: 'Dessert', label: 'Desserts', icon: Cookie },
  { id: 'Sauce', label: 'Sauces', icon: Droplet },
  { id: 'Epices', label: 'Épices & Autres', icon: Utensils },
];

export const detectSmartCategory = (name: string, currentCategory: string = ''): string => {
    const n = name.toLowerCase();
    
    // 0. Nouvelles catégories prioritaires
    if (n.includes('gâteau') || n.includes('tarte') || n.includes('biscuit') || n.includes('dessert') || n.includes('chocolat')) {
        return 'Dessert';
    }
    if ((n.includes('sauce') || n.includes('marinade')) && !n.includes('pâtes') && !n.includes('viande')) {
        return 'Sauce';
    }
    if (n.includes('fondue parmesan') || n.includes('bâtonnet fromage') || n.includes('calmar') || n.includes('aile') || n.includes('entrée') || n.includes('boulette')) {
        return 'Entrée';
    }

    // 1. Épices & Assaisonnements (Requested Priority)
    if (n.includes('épice') || n.includes('epice') || n.includes('rub') || n.includes('assaisonnement') || n.includes('sel ') || n.includes('poivre')) {
        return 'Epices';
    }

    // 2. Prêt-à-manger (Explicit overrides for prepared meals)
    if (n.includes('pâté') || n.includes('lasagne') || n.includes('pizza') || n.includes('tourtière') || n.includes('quiche')) {
        return 'Prêt-à-manger';
    }

    // 3. Specific Poultry keywords (Aileron, Pilon -> Poulet)
    if (n.includes('aileron') || n.includes('pilon') || n.includes('haut de cuisse') || n.includes('poulet') || n.includes('volaille') || n.includes('dinde')) {
        return 'Poulet';
    }

    // 4. Specific Pork keywords (Bacon, Saucisse -> Porc)
    if (n.includes('porc') || n.includes('pork') || n.includes('bacon') || n.includes('saucisse') || n.includes('jambon') || n.includes('cote levée') || n.includes('côte levée') || n.includes('flanc')) {
        return 'Porc';
    }

    // 5. Beef keywords
    if (n.includes('boeuf') || n.includes('bœuf') || n.includes('beef') || n.includes('steak') || n.includes('bavette') || n.includes('ribeye') || n.includes('t-bone') || n.includes('tomahawk') || n.includes('viande fumée') || n.includes('smoked meat') || n.includes('burger')) {
        return 'Boeuf';
    }

    // 6. Fish/Seafood keywords
    if (n.includes('poisson') || n.includes('saumon') || n.includes('truite') || n.includes('morue') || n.includes('crevette') || n.includes('homard') || n.includes('pétoncle') || n.includes('fruit de mer') || n.includes('tilapia') || n.includes('aiglefin')) {
        return 'Poisson/Fruits de mer';
    }

    // 7. Game keywords
    if (n.includes('bison') || n.includes('cerf') || n.includes('canard') || n.includes('agneau') || n.includes('cheval')) {
        return 'Gibier & Autres';
    }

    // Fallback to existing category normalization
    const c = currentCategory.toLowerCase();
    if (c.includes('boeuf')) return 'Boeuf';
    if (c.includes('poulet')) return 'Poulet';
    if (c.includes('porc')) return 'Porc';
    if (c.includes('poisson') || c.includes('mer')) return 'Poisson/Fruits de mer';
    if (c.includes('gibier')) return 'Gibier & Autres';
    if (c.includes('prêt')) return 'Prêt-à-manger';
    if (c.includes('epice')) return 'Epices';
    if (c.includes('dessert')) return 'Dessert';
    if (c.includes('entree') || c.includes('entrée')) return 'Entrée';
    if (c.includes('sauce')) return 'Sauce';

    return currentCategory || 'Autre';
};

// --- PERSONA TEMPLATES (Package Scenarios) ---
export const PERSONA_TEMPLATES = [
    {
        id: 'family_budget',
        label: 'Famille Budget (4p)',
        description: 'Optimisé pour ~275$/sem. Gros formats, mijotés.',
        iconName: 'PiggyBank',
        color: 'green',
        defaultBudget: 275,
        rules: {
            'Boeuf': [
                { keywords: ['haché', 'ground'], freq: 1.0 },
                { keywords: ['cube', 'ragoût', 'stew'], freq: 0.5 },
                { keywords: ['palette', 'rôti'], freq: 0.25 },
                { keywords: ['burger'], freq: 0.25 },
            ],
            'Poulet': [
                { keywords: ['entier', 'whole'], freq: 0.5 },
                { keywords: ['haut de cuisse', 'thigh'], freq: 1.0 },
                { keywords: ['pilon', 'drumstick'], freq: 0.5 },
                { keywords: ['haché'], freq: 0.5 },
            ],
            'Porc': [
                { keywords: ['longe', 'rôti'], freq: 0.25 },
                { keywords: ['saucisse'], freq: 0.5 },
                { keywords: ['haché'], freq: 0.5 },
                { keywords: ['côtelette'], freq: 0.5 },
            ],
            'Extra': [
                { keywords: ['pâté'], freq: 0.25 },
            ]
        }
    },
    {
        id: 'shared_custody',
        label: 'Garde Partagée',
        description: 'Flexible. Plats enfants et repas rapides.',
        iconName: 'UserPlus',
        color: 'orange',
        defaultBudget: 225,
        rules: {
            'Boeuf': [
                { keywords: ['burger'], freq: 1.0 },
                { keywords: ['haché'], freq: 0.5 },
                { keywords: ['minute', 'tournedos'], freq: 0.5 },
            ],
            'Poulet': [
                { keywords: ['croquette', 'nugget'], freq: 1.0 },
                { keywords: ['brochette', 'souvlaki'], freq: 0.5 },
                { keywords: ['pané', 'lanière'], freq: 0.5 },
                { keywords: ['pilon'], freq: 0.5 },
            ],
            'Extra': [
                { keywords: ['pâté'], freq: 0.25 },
                { keywords: ['sauce'], freq: 0.5 },
                { keywords: ['lasagne', 'pizza'], freq: 0.5 },
            ],
            'Dessert': [
                { keywords: ['gâteau'], freq: 0.25 }
            ]
        }
    },
    {
        id: 'essentials',
        label: 'Les 5 Essentiels',
        description: '5 repas simples par semaine. Poulet, Bœuf, Porc.',
        iconName: 'Zap',
        color: 'blue',
        defaultBudget: 200,
        rules: {
            'Boeuf': [
                { keywords: ['haché', 'ground'], freq: 1.0 },
                { keywords: ['bavette'], freq: 0.25 },
                { keywords: ['cube'], freq: 0.25 },
            ],
            'Poulet': [
                { keywords: ['poitrine', 'breast'], freq: 1.0 },
                { keywords: ['pilon'], freq: 0.5 },
            ],
            'Porc': [
                { keywords: ['côtelette', 'chop'], freq: 0.5 },
                { keywords: ['filet'], freq: 0.5 },
            ]
        }
    },
    {
        id: 'premium',
        label: 'Gastronome VIP',
        description: 'Upgrade. Steaks, Fruits de mer, Veau, Canard.',
        iconName: 'Flame',
        color: 'purple',
        defaultBudget: 400,
        rules: {
            'Boeuf': [
                { keywords: ['filet mignon'], freq: 0.5 },
                { keywords: ['ribeye', 'faux-filet'], freq: 0.5 },
                { keywords: ['bavette'], freq: 0.5 },
                { keywords: ['tomahawk', 't-bone'], freq: 0.25 },
            ],
            'Poisson': [
                { keywords: ['pétoncle'], freq: 0.25 },
                { keywords: ['homard', 'crevette'], freq: 0.5 },
                { keywords: ['saumon'], freq: 0.5 },
                { keywords: ['morue', 'aiglefin'], freq: 0.25 },
            ],
             'Gibier & Autres': [
                { keywords: ['veau'], freq: 0.25 },
                { keywords: ['canard'], freq: 0.25 },
                { keywords: ['agneau'], freq: 0.25 }
            ],
            'Entrée': [
                { keywords: ['fondue'], freq: 0.25 }
            ]
        }
    },
    {
        id: 'condo_storage',
        label: 'Espace Condo',
        description: 'Compact. Emballages plats sous-vide.',
        iconName: 'Box',
        color: 'yellow',
        defaultBudget: 250,
        rules: {
            'Boeuf': [
                { keywords: ['bavette'], freq: 0.5 },
                { keywords: ['tournedos'], freq: 0.5 },
                { keywords: ['steak'], freq: 0.5 },
            ],
            'Poulet': [
                { keywords: ['poitrine', 'breast'], freq: 1.0 },
                { keywords: ['tournedos'], freq: 0.5 },
            ],
            'Poisson': [
                { keywords: ['filet'], freq: 1.0 },
            ],
            'Porc': [
                { keywords: ['saucisse'], freq: 0.5 },
                { keywords: ['bacon'], freq: 0.25 },
            ]
        }
    }
];

// --- CATALOGUE USINE (SOURCE UNIQUE DE VÉRITÉ) ---
export const PRODUCT_CATALOG: Product[] = [
  {
    "id": "b_821397",
    "sku": "821397",
    "name": "Bœuf haché extra maigre",
    "format": "10 X 454G",
    "price": 89.9,
    "category": "Boeuf",
    "unitCount": 10,
    "totalWeightGrams": 4540,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "managementCategory": "base"
  },
  {
    "id": "b_1534S",
    "sku": "1534-S",
    "name": "Bœuf Haché Maigre",
    "format": "10 X 454G",
    "price": 83,
    "category": "Boeuf",
    "unitCount": 10,
    "totalWeightGrams": 4540,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "managementCategory": "base"
  },
  {
    "id": "b_811625",
    "sku": "811625",
    "name": "Steak Minute AAA",
    "format": "24 X 110G",
    "price": 150.9,
    "category": "Boeuf",
    "unitCount": 24,
    "totalWeightGrams": 2640,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "base"
  },
  {
    "id": "b_821343",
    "sku": "821343",
    "name": "Cubes de boeuf à ragoût",
    "format": "8 X 454G",
    "price": 146.7,
    "category": "Boeuf",
    "unitCount": 8,
    "totalWeightGrams": 3632,
    "consumptionType": "staple",
    "isAvailable": true,
    "seasonality": "winter",
    "proteinType": "Viande Rouge",
    "texture": "cube",
    "managementCategory": "base"
  },
  {
    "id": "b_fondue",
    "sku": "821999",
    "name": "Cubes pour Fondue Chinoise",
    "format": "10 X 350G",
    "price": 155,
    "category": "Boeuf",
    "unitCount": 10,
    "totalWeightGrams": 3500,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "slice",
    "managementCategory": "medium"
  },
  {
    "id": "b_811930",
    "sku": "811930",
    "name": "Tournedos de boeuf",
    "format": "24 X 110G",
    "price": 186.9,
    "category": "Boeuf",
    "unitCount": 24,
    "totalWeightGrams": 2640,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "base"
  },
  {
    "id": "b_821416",
    "sku": "821416",
    "name": "Bavette de boeuf marinée",
    "format": "12 X 224G",
    "price": 274.7,
    "category": "Boeuf",
    "unitCount": 12,
    "totalWeightGrams": 2688,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "premium"
  },
  {
    "id": "b_821421",
    "sku": "821421",
    "name": "Filet mignon AAA+ 6 oz",
    "format": "12 X 170G",
    "price": 357.9,
    "category": "Boeuf",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "premium"
  },
  {
    "id": "b_ribeye",
    "sku": "821888",
    "name": "Faux-Filet (Ribeye) AAA",
    "format": "10 X 340G",
    "price": 310,
    "category": "Boeuf",
    "unitCount": 10,
    "totalWeightGrams": 3400,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "premium"
  },
  {
    "id": "b_tbone",
    "sku": "821777",
    "name": "T-Bone Steak AAA",
    "format": "8 X 454G",
    "price": 295,
    "category": "Boeuf",
    "unitCount": 8,
    "totalWeightGrams": 3632,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "managementCategory": "premium"
  },
  {
    "id": "b_821368",
    "sku": "821368",
    "name": "Rosette de boeuf",
    "format": "2 kg",
    "price": 91.3,
    "category": "Boeuf",
    "totalWeightGrams": 2000,
    "consumptionType": "roast",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "roast",
    "managementCategory": "base"
  },
  {
    "id": "b_821425",
    "sku": "821425",
    "name": "Roti d'Épaule de Boeuf",
    "format": "3 X 1KG",
    "price": 120.8,
    "category": "Boeuf",
    "unitCount": 3,
    "totalWeightGrams": 3000,
    "consumptionType": "roast",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "roast",
    "managementCategory": "base"
  },
  {
    "id": "b_150322",
    "sku": "150322",
    "name": "Smoked Meat",
    "format": "22 X 125g",
    "price": 238.6,
    "category": "Boeuf",
    "unitCount": 22,
    "totalWeightGrams": 2750,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "deli",
    "managementCategory": "base"
  },
  {
    "id": "821345",
    "sku": "821345",
    "name": "Tournedos de boeuf aux trois poivres",
    "format": "24 X 110G",
    "price": 186.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 24,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "811225",
    "sku": "811225",
    "name": "Contre-filet mariné 3 poivres",
    "format": "12 X 220G",
    "price": 78.3,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "811430",
    "sku": "811430",
    "name": "Bift. Filet mignon châteaubriand",
    "format": "8 X 280G",
    "price": 225.1,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 8,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "821529",
    "sku": "821529",
    "name": "Onglet de boeuf AAA 6 oz",
    "format": "12 x 170G",
    "price": 180.2,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "821530",
    "sku": "821530",
    "name": "Onglet de Boeuf AAA 8 oz",
    "format": "12 x 220G",
    "price": 238.5,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "821527",
    "sku": "821527",
    "name": "Bift. Haut Surlonge 6 oz (Baseball Cut) AAA+",
    "format": "12 x 170 g",
    "price": 180.2,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "821417",
    "sku": "821417",
    "name": "Contre filet 10 oz",
    "format": "12 X 280g",
    "price": 308.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 12,
    "totalWeightGrams": 3360,
    "isAvailable": true
  },
  {
    "id": "821528",
    "sku": "821528",
    "name": "Bift. Haut Surlonge 8 oz (Baseball Cut) AAA+",
    "format": "12 x 220g",
    "price": 242.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "821418",
    "sku": "821418",
    "name": "Contre filet 12 oz",
    "format": "10 X 340g",
    "price": 307.1,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 3400,
    "isAvailable": true
  },
  {
    "id": "821430",
    "sku": "821430",
    "name": "Contre-Filet AA 10oz",
    "format": "10 x 285g",
    "price": 216.1,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2850,
    "isAvailable": true
  },
  {
    "id": "821423",
    "sku": "821423",
    "name": "Filet mignon AAA+ 8 oz",
    "format": "10 X 224G",
    "price": 394.7,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "821422",
    "sku": "821422",
    "name": "Filet Mignon AAA+ 10 oz",
    "format": "8 X 280G",
    "price": 399.99,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 8,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "821431",
    "sku": "821431",
    "name": "Filet mignon AA 6 oz",
    "format": "12 x 170g",
    "price": 335.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "821420",
    "sku": "821420",
    "name": "Faux filet AAA 10 oz",
    "format": "10 X 285g",
    "price": 301.6,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 2850,
    "isAvailable": true
  },
  {
    "id": "1501955",
    "sku": "1501955",
    "name": "BF Contre Filet CAB prime",
    "format": "12 X 225G",
    "price": 399.99,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 12,
    "totalWeightGrams": 2700,
    "isAvailable": true
  },
  {
    "id": "1501684",
    "sku": "1501684",
    "name": "Haut Surlonge CAB PRIME",
    "format": "10 X 170G",
    "price": 267.5,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 1700,
    "isAvailable": true
  },
  {
    "id": "821436",
    "sku": "821436",
    "name": "Bift. D'Aloyau T-Bone 3/4\"",
    "format": "4 X 460g",
    "price": 216.5,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 4,
    "totalWeightGrams": 1840,
    "isAvailable": true
  },
  {
    "id": "821427",
    "sku": "821427",
    "name": "Bift. D'Aloyau 1-1/2\" T-Bone",
    "format": "4 X 850G",
    "price": 399.99,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 4,
    "totalWeightGrams": 3400,
    "isAvailable": true
  },
  {
    "id": "821432",
    "sku": "821432",
    "name": "T-Bone AA 3/4po",
    "format": "4 x 450g",
    "price": 234.5,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 4,
    "totalWeightGrams": 1800,
    "isAvailable": true
  },
  {
    "id": "821426",
    "sku": "821426",
    "name": "Rib tomahawk AAA",
    "format": "2 X 1.3KG",
    "price": 256,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 2,
    "totalWeightGrams": 2600,
    "isAvailable": true
  },
  {
    "id": "821429",
    "sku": "821429",
    "name": "Bifteck de côte 1\"",
    "format": "6 X 570G",
    "price": 359.5,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 6,
    "totalWeightGrams": 3420,
    "isAvailable": true
  },
  {
    "id": "821419",
    "sku": "821419",
    "name": "Bifteck de côte 1\"1/2",
    "format": "4 X 815 g",
    "price": 342.7,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 4,
    "totalWeightGrams": 3260,
    "isAvailable": true
  },
  {
    "id": "821914",
    "sku": "821914",
    "name": "Cote Cowboy CAB PRIME",
    "format": "4 X 454G",
    "price": 229.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 4,
    "totalWeightGrams": 1816,
    "isAvailable": true
  },
  {
    "id": "1900-s",
    "sku": "1900-s",
    "name": "Galettes de boeuf",
    "format": "10 x (2 x 170g)",
    "price": 100.4,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "consumptionType": "quick",
    "unitCount": 20,
    "totalWeightGrams": 3400,
    "isAvailable": true
  },
  {
    "id": "821661",
    "sku": "821661",
    "name": "Wagyu kobe A5 Mix",
    "format": "2 x 200g",
    "price": 243.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 2,
    "totalWeightGrams": 400,
    "isAvailable": true
  },
  {
    "id": "1501340",
    "sku": "1501340",
    "name": "Haut De Surlonge Wagyu",
    "format": "10 x 170G",
    "price": 442.9,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 1700,
    "isAvailable": true
  },
  {
    "id": "p_QC10608",
    "sku": "QC10608",
    "name": "Haut Cuisse poulet désossé",
    "format": "10-14 (3,6 kg)",
    "price": 127,
    "category": "Poulet",
    "unitCount": 12,
    "totalWeightGrams": 3600,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "piece",
    "managementCategory": "base"
  },
  {
    "id": "p_QC10114",
    "sku": "QC10114",
    "name": "Poitrines poulet désossées",
    "format": "9-12 (3.2KG)",
    "price": 109,
    "category": "Poulet",
    "unitCount": 10,
    "totalWeightGrams": 3200,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "breast",
    "managementCategory": "base"
  },
  {
    "id": "p_hache",
    "sku": "QC10999",
    "name": "Poulet Haché Maigre",
    "format": "10 X 454G",
    "price": 95,
    "category": "Poulet",
    "unitCount": 10,
    "totalWeightGrams": 4540,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "ground",
    "managementCategory": "base"
  },
  {
    "id": "p_QC11009",
    "sku": "QC11009",
    "name": "Poulet entier 1,8 kg",
    "format": "1,8 Kg",
    "price": 17.4,
    "category": "Poulet",
    "unitCount": 1,
    "totalWeightGrams": 1800,
    "consumptionType": "roast",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "whole",
    "managementCategory": "base"
  },
  {
    "id": "p_811425",
    "sku": "811425",
    "name": "Brochettes poulet souvlaki",
    "format": "18 X 110G",
    "price": 133.7,
    "category": "Poulet",
    "unitCount": 18,
    "totalWeightGrams": 1980,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "kebab",
    "managementCategory": "base"
  },
  {
    "id": "p_821369",
    "sku": "821369",
    "name": "Ailes de poulet BBQ",
    "format": "2 X 1KG",
    "price": 76.9,
    "category": "Poulet",
    "unitCount": 2,
    "totalWeightGrams": 2000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "bone-in",
    "managementCategory": "base"
  },
  {
    "id": "p_croq",
    "sku": "821555",
    "name": "Croquettes de Poulet (Vraie viande)",
    "format": "4 X 1KG",
    "price": 85,
    "category": "Poulet",
    "unitCount": 4,
    "totalWeightGrams": 4000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "prepared",
    "managementCategory": "base"
  },
  {
    "id": "p_gen",
    "sku": "821666",
    "name": "Poulet Général Tao",
    "format": "4 X 1KG",
    "price": 92,
    "category": "Poulet",
    "unitCount": 4,
    "totalWeightGrams": 4000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "prepared",
    "managementCategory": "base"
  },
  {
    "id": "QC10214",
    "sku": "QC10214",
    "name": "Poulet Cuisse S/D",
    "format": "8-10 (4,2KG)",
    "price": 74.5,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "staple",
    "unitCount": 9,
    "totalWeightGrams": 4200,
    "isAvailable": true
  },
  {
    "id": "QC10414",
    "sku": "QC10414",
    "name": "Pilons de Poulet de Grain",
    "format": "4-6 pqt (4,2 kg)",
    "price": 79.1,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "staple",
    "unitCount": 5,
    "totalWeightGrams": 4200,
    "isAvailable": true
  },
  {
    "id": "10009",
    "sku": "10009",
    "name": "Poulet de grain entier 3 kg",
    "format": "3 KG",
    "price": 46,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "whole",
    "consumptionType": "roast",
    "unitCount": 1,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "QC10316",
    "sku": "QC10316",
    "name": "Ailes de Poulet de Grain",
    "format": "6 x 450G",
    "price": 71.6,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "bone-in",
    "consumptionType": "quick",
    "unitCount": 6,
    "totalWeightGrams": 2700,
    "isAvailable": true
  },
  {
    "id": "821342",
    "sku": "821342",
    "name": "Cubes de brochette de poulet",
    "format": "10 X 224G",
    "price": 140.9,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "cube",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "821333",
    "sku": "821333",
    "name": "Escalopes de poulet",
    "format": "20 X 110G",
    "price": 123.4,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 20,
    "totalWeightGrams": 2200,
    "isAvailable": true
  },
  {
    "id": "QC10955",
    "sku": "QC10955",
    "name": "Poulet de grain Haché",
    "format": "6 x 450G",
    "price": 85.7,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 6,
    "totalWeightGrams": 2700,
    "isAvailable": true
  },
  {
    "id": "151639",
    "sku": "151639",
    "name": "Dinde Hachée",
    "format": "6 x 454G",
    "price": 79.1,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 6,
    "totalWeightGrams": 2724,
    "isAvailable": true
  },
  {
    "id": "811574",
    "sku": "811574",
    "name": "Tournedos de poulet (nature)",
    "format": "16 X 142G",
    "price": 163.2,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 16,
    "totalWeightGrams": 2272,
    "isAvailable": true
  },
  {
    "id": "821352",
    "sku": "821352",
    "name": "Tournedos de poulet miel et ail",
    "format": "16 X 140G",
    "price": 176.8,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 16,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "821334",
    "sku": "821334",
    "name": "Tournedos de poulet méditéranéen",
    "format": "14 x 170G",
    "price": 176.8,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 14,
    "totalWeightGrams": 2380,
    "isAvailable": true
  },
  {
    "id": "821338",
    "sku": "821338",
    "name": "Tournedos de poulet (BBQ)",
    "format": "16 x 140G",
    "price": 170,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 16,
    "totalWeightGrams": 2240,
    "isAvailable": true
  },
  {
    "id": "811347",
    "sku": "811347",
    "name": "Poitrine de poulet et BBQ",
    "format": "12 X 170G",
    "price": 107.3,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "811346",
    "sku": "811346",
    "name": "Poitrine de poulet miel & ail",
    "format": "8 x 255 g",
    "price": 104.9,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "811353",
    "sku": "811353",
    "name": "poitrine de poulet méditerranéenne",
    "format": "12 x 170g",
    "price": 125,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "821373",
    "sku": "821373",
    "name": "Poulet pop corn",
    "format": "2KG",
    "price": 84.2,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821340",
    "sku": "821340",
    "name": "Croquettes de poulet",
    "format": "2 X 1KG",
    "price": 69,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821409",
    "sku": "821409",
    "name": "Filet de poulet pané",
    "format": "2kg",
    "price": 92.9,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821374",
    "sku": "821374",
    "name": "Burger de poulet pané",
    "format": "1.6 KG",
    "price": 92.9,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 1600,
    "isAvailable": true
  },
  {
    "id": "221009",
    "sku": "221009",
    "name": "Poulet Pané Style maison",
    "format": "2,2 Kg",
    "price": 79.1,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 2200,
    "isAvailable": true
  },
  {
    "id": "821369_2",
    "sku": "821369",
    "name": "Ailes de poulet BBQ",
    "format": "2 X 1KG",
    "price": 76.9,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "bone-in",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "221010",
    "sku": "221010",
    "name": "Poitrine de poulet farcie jambon fromage",
    "format": "2.04 KG (entre 10-12unite)",
    "price": 158.1,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 11,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "221012",
    "sku": "221012",
    "name": "Poitrine de poulet farcie brocoli fromage",
    "format": "10 X 270G",
    "price": 158.1,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2700,
    "isAvailable": true
  },
  {
    "id": "811002",
    "sku": "811002",
    "name": "Coq au porc érable & chipotle",
    "format": "12 X 275G",
    "price": 170.3,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 3300,
    "isAvailable": true
  },
  {
    "id": "162101",
    "sku": "162101",
    "name": "Dinde Assaisonnée Cuite",
    "format": "5,6 KG",
    "price": 142.4,
    "category": "Poulet",
    "proteinType": "Volaille",
    "texture": "roast",
    "consumptionType": "roast",
    "unitCount": 1,
    "totalWeightGrams": 5600,
    "isAvailable": true
  },
  {
    "id": "po_151396",
    "sku": "151396",
    "name": "Porc haché 85%",
    "format": "10 X 500G",
    "price": 80.5,
    "category": "Porc",
    "unitCount": 10,
    "totalWeightGrams": 5000,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "ground",
    "managementCategory": "base"
  },
  {
    "id": "po_filet",
    "sku": "811222",
    "name": "Filet de Porc (Tenderloin)",
    "format": "4 X 1KG",
    "price": 88,
    "category": "Porc",
    "unitCount": 8,
    "totalWeightGrams": 4000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "piece",
    "managementCategory": "base"
  },
  {
    "id": "po_811975",
    "sku": "811975",
    "name": "Rôti de porc longe",
    "format": "4 X 908G",
    "price": 51.8,
    "category": "Porc",
    "unitCount": 4,
    "totalWeightGrams": 3632,
    "consumptionType": "roast",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "roast",
    "managementCategory": "base"
  },
  {
    "id": "po_821524",
    "sku": "821524",
    "name": "Bacon artisanal",
    "format": "6 X 500g",
    "price": 76.2,
    "category": "Porc",
    "unitCount": 6,
    "totalWeightGrams": 3000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "slice",
    "managementCategory": "base"
  },
  {
    "id": "po_821252",
    "sku": "821252",
    "name": "Côte de porc bbq",
    "format": "12 x 250g",
    "price": 101.4,
    "category": "Porc",
    "unitCount": 12,
    "totalWeightGrams": 3000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "chop",
    "managementCategory": "base"
  },
  {
    "id": "po_saucisse_it",
    "sku": "821111",
    "name": "Saucisses Italiennes Douces",
    "format": "5kg (VRAC)",
    "price": 65,
    "category": "Porc",
    "totalWeightGrams": 5000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "sausage",
    "managementCategory": "base"
  },
  {
    "id": "po_saucisse_dj",
    "sku": "821112",
    "name": "Saucisses Déjeuner Érable",
    "format": "5kg (VRAC)",
    "price": 68,
    "category": "Porc",
    "totalWeightGrams": 5000,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Porc",
    "texture": "sausage",
    "managementCategory": "base"
  },
  {
    "id": "821351",
    "sku": "821351",
    "name": "Filet mignon de porc",
    "format": "5-6 (3 kg)",
    "price": 54.99,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 6,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "150236",
    "sku": "150236",
    "name": "Côte de porc manchon",
    "format": "approx 12 X +/-300G",
    "price": 186.9,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 3600,
    "isAvailable": true
  },
  {
    "id": "151125",
    "sku": "151125",
    "name": "Escalope de porc attendri",
    "format": "24 x 110G",
    "price": 66.9,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 24,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "811301",
    "sku": "811301",
    "name": "Côtelettes de porc demi-lune",
    "format": "24 x 110G",
    "price": 67.1,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 24,
    "totalWeightGrams": 2640,
    "isAvailable": true
  },
  {
    "id": "821346",
    "sku": "821346",
    "name": "Côtes levées de porc entières nature",
    "format": "5 X +/-850G",
    "price": 111.8,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "ribs",
    "consumptionType": "quick",
    "unitCount": 5,
    "totalWeightGrams": 4250,
    "isAvailable": true
  },
  {
    "id": "851350",
    "sku": "851350",
    "name": "Échine de Porc",
    "format": "4 X 750G",
    "price": 118.6,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "roast",
    "consumptionType": "roast",
    "unitCount": 4,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "821350",
    "sku": "821350",
    "name": "Côtelette de porc avec os",
    "format": "12 x 140G",
    "price": 46,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 1680,
    "isAvailable": true
  },
  {
    "id": "811104",
    "sku": "811104",
    "name": "Brochettes de porc souvlaki",
    "format": "9 x 2 x 110G",
    "price": 84.3,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "kebab",
    "consumptionType": "quick",
    "unitCount": 18,
    "totalWeightGrams": 1980,
    "isAvailable": true
  },
  {
    "id": "102499",
    "sku": "102499",
    "name": "Bacon tranché cov",
    "format": "10 x 250G",
    "price": 113.5,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2500,
    "isAvailable": true
  },
  {
    "id": "821251",
    "sku": "821251",
    "name": "Côte de porc teriyaki",
    "format": "12 x 250g",
    "price": 101.4,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "821250",
    "sku": "821250",
    "name": "Côte de porc érable chipotlé",
    "format": "12 x 250g",
    "price": 101.4,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "821331",
    "sku": "821331",
    "name": "Côtelette De Porc A/Os Souvlaki",
    "format": "8 X 400G",
    "price": 102.8,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 3200,
    "isAvailable": true
  },
  {
    "id": "821332",
    "sku": "821332",
    "name": "Côtelette De Porc A/Os Teriyaki",
    "format": "8 X 400G",
    "price": 102.8,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "chop",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 3200,
    "isAvailable": true
  },
  {
    "id": "6031-s",
    "sku": "6031-s",
    "name": "Osso Bucco de Porc",
    "format": "12 X 275G",
    "price": 94.6,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "piece",
    "consumptionType": "slow",
    "unitCount": 12,
    "totalWeightGrams": 3300,
    "isAvailable": true
  },
  {
    "id": "150708",
    "sku": "150708",
    "name": "Porc effiloché a la texane",
    "format": "8 x 500g",
    "price": 169.6,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 4000,
    "isAvailable": true
  },
  {
    "id": "321372",
    "sku": "321372",
    "name": "Côte levée quatre côtes BBQ",
    "format": "10 X 250G",
    "price": 154.6,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "ribs",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2500,
    "isAvailable": true
  },
  {
    "id": "104082",
    "sku": "104082",
    "name": "Saucisse Italienne douce porc",
    "format": "32 X 2 X 90G",
    "price": 149.5,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "sausage",
    "consumptionType": "quick",
    "unitCount": 64,
    "totalWeightGrams": 5760,
    "isAvailable": true
  },
  {
    "id": "104084",
    "sku": "104084",
    "name": "Saucisse Toulouse",
    "format": "16 X 4 X 90G",
    "price": 153.8,
    "category": "Porc",
    "proteinType": "Porc",
    "texture": "sausage",
    "consumptionType": "quick",
    "unitCount": 64,
    "totalWeightGrams": 5760,
    "isAvailable": true
  },
  {
    "id": "f_821256",
    "sku": "821256",
    "name": "Pavé de saumon Atlantique",
    "format": "12 X 170G",
    "price": 95.9,
    "category": "Poisson/Fruits de mer",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Poissons",
    "texture": "fillet",
    "managementCategory": "base"
  },
  {
    "id": "f_truite",
    "sku": "821300",
    "name": "Filet de Truite Arc-en-ciel",
    "format": "10 X 200G",
    "price": 98.5,
    "category": "Poisson/Fruits de mer",
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Poissons",
    "texture": "fillet",
    "managementCategory": "base"
  },
  {
    "id": "f_morue",
    "sku": "821301",
    "name": "Dos de Morue Islande",
    "format": "10 X 170G",
    "price": 115,
    "category": "Poisson/Fruits de mer",
    "unitCount": 10,
    "totalWeightGrams": 1700,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Poissons",
    "texture": "fillet",
    "managementCategory": "medium"
  },
  {
    "id": "f_821347",
    "sku": "821347",
    "name": "Crevettes nordiques cuites",
    "format": "5 X 400G",
    "price": 134.4,
    "category": "Poisson/Fruits de mer",
    "unitCount": 5,
    "totalWeightGrams": 2000,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Fruits de mer",
    "texture": "small",
    "managementCategory": "base"
  },
  {
    "id": "f_tigre",
    "sku": "821348",
    "name": "Crevettes Tigrées (Crues, 16-20)",
    "format": "2 X 908G",
    "price": 89,
    "category": "Poisson/Fruits de mer",
    "totalWeightGrams": 1816,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "managementCategory": "medium"
  },
  {
    "id": "f_petoncle",
    "sku": "821349",
    "name": "Pétoncles Géants U-10",
    "format": "2 X 1KG",
    "price": 145,
    "category": "Poisson/Fruits de mer",
    "totalWeightGrams": 2000,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "managementCategory": "premium"
  },
  {
    "id": "f_821714",
    "sku": "821714",
    "name": "Queue de homard",
    "format": "1.82KG",
    "price": 314.9,
    "category": "Poisson/Fruits de mer",
    "totalWeightGrams": 1820,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Fruits de mer",
    "texture": "whole",
    "managementCategory": "premium"
  },
  {
    "id": "821666",
    "sku": "821666",
    "name": "Omble Chevalier",
    "format": "2 Kg",
    "price": 105,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 1,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821532",
    "sku": "821532",
    "name": "Saumon biologique king A/P",
    "format": "10 UNITÉ / 6 OZ",
    "price": 137.6,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 10,
    "totalWeightGrams": 1700,
    "isAvailable": true
  },
  {
    "id": "821257",
    "sku": "821257",
    "name": "Filet de truite",
    "format": "8-11 (1,82KG)",
    "price": 118.7,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 9,
    "totalWeightGrams": 1820,
    "isAvailable": true
  },
  {
    "id": "821324",
    "sku": "821324",
    "name": "Thon saku 8 oz",
    "format": "6 X 225G",
    "price": 195,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 6,
    "totalWeightGrams": 1350,
    "isAvailable": true
  },
  {
    "id": "821269",
    "sku": "821269",
    "name": "Flétan",
    "format": "8 X 170G",
    "price": 211.4,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 1360,
    "isAvailable": true
  },
  {
    "id": "821652",
    "sku": "821652",
    "name": "Bajoue De Morue",
    "format": "8 X 250G",
    "price": 186.9,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "piece",
    "consumptionType": "staple",
    "unitCount": 8,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821298",
    "sku": "821298",
    "name": "Longe de morue 5 oz",
    "format": "12 unité",
    "price": 94.6,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 12,
    "totalWeightGrams": 1700,
    "isAvailable": true
  },
  {
    "id": "211565",
    "sku": "211565",
    "name": "Longe d'aiglefin",
    "format": "16 X 4 oz (1,82 Kg)",
    "price": 81,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 16,
    "totalWeightGrams": 1820,
    "isAvailable": true
  },
  {
    "id": "821203",
    "sku": "821203",
    "name": "Filet de sole",
    "format": "20 X 3OZ",
    "price": 84.3,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 20,
    "totalWeightGrams": 1700,
    "isAvailable": true
  },
  {
    "id": "821316",
    "sku": "821316",
    "name": "Filet de doré",
    "format": "(10-13) 2KG",
    "price": 139.3,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 11,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821233",
    "sku": "821233",
    "name": "Tilapia",
    "format": "2 lbs (908g)",
    "price": 17.1,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "staple",
    "unitCount": 1,
    "totalWeightGrams": 908,
    "isAvailable": true
  },
  {
    "id": "812625",
    "sku": "812625",
    "name": "Darnes Espadon",
    "format": "12 X 170G",
    "price": 153.1,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "821526",
    "sku": "821526",
    "name": "Mahi-mahi",
    "format": "12 X 170G",
    "price": 135.9,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "812652",
    "sku": "812652",
    "name": "Vivaneau",
    "format": "10 X 200G",
    "price": 166.7,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821319",
    "sku": "821319",
    "name": "Brochette de saumon à l'érable",
    "format": "12 X 175G",
    "price": 170.3,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "kebab",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2100,
    "isAvailable": true
  },
  {
    "id": "821320",
    "sku": "821320",
    "name": "Brochette de saumon trois poivres",
    "format": "12 X 175G",
    "price": 170.3,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "kebab",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2100,
    "isAvailable": true
  },
  {
    "id": "1483627",
    "sku": "1483627",
    "name": "Gravlax de Saumon tranché",
    "format": "12 X 100G",
    "price": 181.2,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 1200,
    "isAvailable": true
  },
  {
    "id": "1340113",
    "sku": "1340113",
    "name": "Saumon Coho Fumé Tranché",
    "format": "15 X 70G",
    "price": 137.6,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 15,
    "totalWeightGrams": 1050,
    "isAvailable": true
  },
  {
    "id": "1073712",
    "sku": "1073712",
    "name": "Truite fumée tranchée",
    "format": "15 x 70G",
    "price": 184,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 15,
    "totalWeightGrams": 1050,
    "isAvailable": true
  },
  {
    "id": "1318018",
    "sku": "1318018",
    "name": "Bonbons Saumon Fumé Érable",
    "format": "14 X 141G",
    "price": 166.2,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 14,
    "totalWeightGrams": 1974,
    "isAvailable": true
  },
  {
    "id": "821323",
    "sku": "821323",
    "name": "Saumon fumé Coho",
    "format": "6-7 un (1,5 Kg)",
    "price": 154.7,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "slice",
    "consumptionType": "quick",
    "unitCount": 6,
    "totalWeightGrams": 1500,
    "isAvailable": true
  },
  {
    "id": "821355",
    "sku": "821355",
    "name": "Saumon planche de cèdre érable et BBQ",
    "format": "8 X 220G",
    "price": 154.8,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 1760,
    "isAvailable": true
  },
  {
    "id": "821353",
    "sku": "821353",
    "name": "Bâtonnets de poisson",
    "format": "2,27KG",
    "price": 91.4,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 2270,
    "isAvailable": true
  },
  {
    "id": "213178",
    "sku": "213178",
    "name": "Fish and chips (morue)",
    "format": "2 x 1KG",
    "price": 256,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "213136",
    "sku": "213136",
    "name": "Fish and chips (goberge)",
    "format": "3 x 1KG",
    "price": 152.4,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 3,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "821321",
    "sku": "821321",
    "name": "Filet de sole au crabe sauce safran",
    "format": "8 X 200G",
    "price": 233.9,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 8,
    "totalWeightGrams": 1600,
    "isAvailable": true
  },
  {
    "id": "610351",
    "sku": "610351",
    "name": "Truite farcie crevette et pétoncle",
    "format": "10 X 200G",
    "price": 194.1,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821375",
    "sku": "821375",
    "name": "Crevette argentine P.D. S/Q 16/20",
    "format": "2 X 908G",
    "price": 152.4,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 1816,
    "isAvailable": true
  },
  {
    "id": "822625",
    "sku": "822625",
    "name": "Crevettes Blanches 16/20 P&D",
    "format": "2 X 908G",
    "price": 129,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 1816,
    "isAvailable": true
  },
  {
    "id": "821318",
    "sku": "821318",
    "name": "Crevettes papillon ail et fines herbes",
    "format": "1.82KG",
    "price": 180.5,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 1820,
    "isAvailable": true
  },
  {
    "id": "821376",
    "sku": "821376",
    "name": "Crevette tigré 16-20",
    "format": "2 X 908G",
    "price": 151,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "quick",
    "unitCount": 2,
    "totalWeightGrams": 1816,
    "isAvailable": true
  },
  {
    "id": "821322",
    "sku": "821322",
    "name": "Queue de langouste 4 oz",
    "format": "1.4KG",
    "price": 256,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 1,
    "totalWeightGrams": 1400,
    "isAvailable": true
  },
  {
    "id": "821531",
    "sku": "821531",
    "name": "Pétoncle 10/20 IQF naturel",
    "format": "2 X 1KG",
    "price": 307.7,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 2,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821348",
    "sku": "821348",
    "name": "Pétoncle 80/120 IQF",
    "format": "5 X 400G",
    "price": 104.9,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Fruits de mer",
    "texture": "shellfish",
    "consumptionType": "staple",
    "unitCount": 5,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821523",
    "sku": "821523",
    "name": "Steak de Thon Rouge 6 oz",
    "format": "13 x 170G",
    "price": 140.9,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 13,
    "totalWeightGrams": 2210,
    "isAvailable": true
  },
  {
    "id": "8250",
    "sku": "8250",
    "name": "Pavé Saumon Fumé",
    "format": "10 X 200G",
    "price": 194.1,
    "category": "Poisson/Fruits de mer",
    "proteinType": "Poissons",
    "texture": "fillet",
    "consumptionType": "quick",
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "g_bison_hache",
    "sku": "GB001",
    "name": "Bison Haché maigre",
    "format": "10 X 454g",
    "price": 145,
    "category": "Gibier & Autres",
    "unitCount": 10,
    "totalWeightGrams": 4540,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Gibier",
    "texture": "ground",
    "managementCategory": "high"
  },
  {
    "id": "g_canard_conf",
    "sku": "GB002",
    "name": "Cuisses de Canard confites",
    "format": "6 X 200g",
    "price": 89,
    "category": "Gibier & Autres",
    "unitCount": 6,
    "totalWeightGrams": 1200,
    "consumptionType": "quick",
    "isAvailable": true,
    "isPremium": true,
    "proteinType": "Volaille",
    "texture": "piece",
    "managementCategory": "premium"
  },
  {
    "id": "MG522617",
    "sku": "MG522617",
    "name": "Médaillon de bison",
    "format": "10 X 200G",
    "price": 236.2,
    "category": "Gibier & Autres",
    "proteinType": "Gibier",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "MG522616",
    "sku": "MG522616",
    "name": "Medaillon de cerf",
    "format": "10 x 200G",
    "price": 163.8,
    "category": "Gibier & Autres",
    "proteinType": "Gibier",
    "texture": "steak",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821354",
    "sku": "821354",
    "name": "Canard cuisse confite",
    "format": "10 x 200G",
    "price": 195.5,
    "category": "Gibier & Autres",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 10,
    "totalWeightGrams": 2000,
    "isAvailable": true
  },
  {
    "id": "821330",
    "sku": "821330",
    "name": "Magret de canard",
    "format": "6 x 400G",
    "price": 175.4,
    "category": "Gibier & Autres",
    "proteinType": "Volaille",
    "texture": "breast",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 6,
    "totalWeightGrams": 2400,
    "isAvailable": true
  },
  {
    "id": "812033",
    "sku": "812033",
    "name": "Pilons de canard fumé",
    "format": "4 X 10 pilons (600g)",
    "price": 111.8,
    "category": "Gibier & Autres",
    "proteinType": "Volaille",
    "texture": "piece",
    "consumptionType": "quick",
    "unitCount": 4,
    "totalWeightGrams": 2400,
    "isAvailable": true
  },
  {
    "id": "821327",
    "sku": "821327",
    "name": "Tourte au canard confit",
    "format": "12 X 170G",
    "price": 273.2,
    "category": "Gibier & Autres",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "isPremium": true,
    "unitCount": 12,
    "totalWeightGrams": 2040,
    "isAvailable": true
  },
  {
    "id": "121487",
    "sku": "121487",
    "name": "Cheval haché",
    "format": "8 X 454G",
    "price": 114.1,
    "category": "Gibier & Autres",
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 8,
    "totalWeightGrams": 3632,
    "isAvailable": true
  },
  {
    "id": "MG923832",
    "sku": "MG923832",
    "name": "Cerf haché extra maigre",
    "format": "10 X 300G",
    "price": 173.6,
    "category": "Gibier & Autres",
    "proteinType": "Gibier",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 10,
    "totalWeightGrams": 3000,
    "isAvailable": true
  },
  {
    "id": "7267321",
    "sku": "7267321",
    "name": "Agneau Haché",
    "format": "4 X 375G",
    "price": 85.9,
    "category": "Gibier & Autres",
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 4,
    "totalWeightGrams": 1500,
    "isAvailable": true
  },
  {
    "id": "508013",
    "sku": "508013",
    "name": "Veau haché",
    "format": "6 X 454G",
    "price": 85.7,
    "category": "Gibier & Autres",
    "proteinType": "Viande Rouge",
    "texture": "ground",
    "consumptionType": "staple",
    "unitCount": 6,
    "totalWeightGrams": 2724,
    "isAvailable": true
  },
  {
    "id": "pm_821379",
    "sku": "821379",
    "name": "Lasagne à la viande",
    "format": "8 X 350G",
    "price": 118.7,
    "category": "Prêt-à-manger",
    "unitCount": 8,
    "totalWeightGrams": 2800,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "prepared",
    "managementCategory": "base"
  },
  {
    "id": "pm_pat",
    "sku": "821380",
    "name": "Pâté au Poulet (Format Familial)",
    "format": "4 X 800G",
    "price": 68,
    "category": "Prêt-à-manger",
    "unitCount": 4,
    "totalWeightGrams": 3200,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Volaille",
    "texture": "prepared",
    "managementCategory": "base"
  },
  {
    "id": "pm_shep",
    "sku": "821381",
    "name": "Pâté Chinois (Shepherd's Pie)",
    "format": "8 X 400G",
    "price": 85,
    "category": "Prêt-à-manger",
    "unitCount": 8,
    "totalWeightGrams": 3200,
    "consumptionType": "quick",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "prepared",
    "managementCategory": "base"
  },
  {
    "id": "pm_sauce",
    "sku": "821382",
    "name": "Sauce à Spaghetti (Viande)",
    "format": "4 X 1L",
    "price": 55,
    "category": "Prêt-à-manger",
    "totalWeightGrams": 4000,
    "consumptionType": "staple",
    "isAvailable": true,
    "proteinType": "Viande Rouge",
    "texture": "liquid",
    "managementCategory": "base"
  },
  {
    "id": "70358",
    "sku": "70358",
    "name": "Sauce à spaghetti au poulet de grain",
    "format": "10 sac x 500 ml",
    "price": 99.9,
    "category": "Prêt-à-manger",
    "proteinType": "Volaille",
    "texture": "liquid",
    "consumptionType": "staple",
    "unitCount": 10,
    "totalWeightGrams": 5000,
    "isAvailable": true
  },
  {
    "id": "221015",
    "sku": "221015",
    "name": "Pâté au poulet",
    "format": "600g",
    "price": 24.4,
    "category": "Prêt-à-manger",
    "proteinType": "Volaille",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 600,
    "isAvailable": true
  },
  {
    "id": "MG920165",
    "sku": "MG920165",
    "name": "Tourtière aux quatres gibiers",
    "format": "840 gr",
    "price": 23.2,
    "category": "Prêt-à-manger",
    "proteinType": "Gibier",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 840,
    "isAvailable": true
  },
  {
    "id": "861276",
    "sku": "861276",
    "name": "Fondu parmesan",
    "format": "12 X 4",
    "price": 115.3,
    "category": "Prêt-à-manger",
    "proteinType": "Laitier",
    "texture": "prepared",
    "consumptionType": "quick",
    "isAppetizer": true,
    "unitCount": 48,
    "totalWeightGrams": 0,
    "isAvailable": true
  },
  {
    "id": "821732",
    "sku": "821732",
    "name": "Pâté au saumon",
    "format": "750G",
    "price": 22.2,
    "category": "Prêt-à-manger",
    "proteinType": "Poissons",
    "texture": "prepared",
    "consumptionType": "quick",
    "unitCount": 1,
    "totalWeightGrams": 750,
    "isAvailable": true
  },
  {
    "id": "821365",
    "sku": "821365",
    "name": "Sauce aux fruits de mer",
    "format": "12 X 270G",
    "price": 133.7,
    "category": "Prêt-à-manger",
    "proteinType": "Fruits de mer",
    "texture": "liquid",
    "consumptionType": "staple",
    "unitCount": 12,
    "totalWeightGrams": 3240,
    "isAvailable": true
  },
  {
    "id": "821364",
    "sku": "821364",
    "name": "Sauce à spaghetti",
    "format": "5 X 1KG",
    "price": 100.6,
    "category": "Prêt-à-manger",
    "proteinType": "Viande Rouge",
    "texture": "liquid",
    "consumptionType": "staple",
    "unitCount": 5,
    "totalWeightGrams": 5000,
    "isAvailable": true
  },
  {
    "id": "0440285",
    "sku": "0440285",
    "name": "Joue de Boeuf",
    "format": "8 x 320g",
    "price": 179.7,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "piece",
    "consumptionType": "slow",
    "unitCount": 8,
    "totalWeightGrams": 2560,
    "isAvailable": true
  },
  {
    "id": "821424",
    "sku": "821424",
    "name": "Macreuse de boeuf AAA",
    "format": "12 X 190G",
    "price": 242.3,
    "category": "Boeuf",
    "proteinType": "Viande Rouge",
    "texture": "steak",
    "consumptionType": "quick",
    "unitCount": 12,
    "totalWeightGrams": 2280,
    "isAvailable": true
  }
];
