import React from 'react';
import { UserCheck, Phone, Mail, MapPin } from 'lucide-react';
import { ClientInfo } from '../types';

interface ClientSectionProps {
  clientInfo: ClientInfo;
  setClientInfo: (info: ClientInfo) => void;
}

export const ClientSection: React.FC<ClientSectionProps> = ({ clientInfo, setClientInfo }) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => { const { name, value } = e.target; setClientInfo({ ...clientInfo, [name]: value }); };
  return (<div className="p-6 bg-white rounded-2xl shadow-sm border border-gray-100 animate-in fade-in slide-in-from-bottom-4 w-full mx-auto"><h2 className="text-2xl font-bold text-slate-800 mb-6 flex items-center gap-3"><UserCheck className="w-7 h-7 text-red-600" /> Informations du Client</h2><div className="space-y-6"><div className="grid md:grid-cols-2 gap-6"><div className="space-y-4"><label className="block"><span className="text-sm font-bold text-slate-700">Contact principal</span><input type="text" name="contactPrincipal" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border" value={clientInfo.contactPrincipal} onChange={handleChange} placeholder="Prénom Nom" /></label><label className="block"><span className="text-sm font-bold text-slate-700">Téléphone</span><div className="flex items-center"><Phone className="w-4 h-4 text-gray-400 mr-2" /><input type="tel" name="telephone" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border" value={clientInfo.telephone} onChange={handleChange} placeholder="(555) 555-5555" /></div></label><label className="block"><span className="text-sm font-bold text-slate-700">Courriel</span><div className="flex items-center"><Mail className="w-4 h-4 text-gray-400 mr-2" /><input type="email" name="courriel" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border" value={clientInfo.courriel} onChange={handleChange} placeholder="exemple@courriel.com" /></div></label></div><div className="space-y-4"><label className="block"><span className="text-sm font-bold text-slate-700">Nom Complet Client 2</span><input type="text" name="client2" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border" value={clientInfo.client2} onChange={handleChange} placeholder="Prénom Nom (Optionnel)" /></label></div></div><div className="border-t border-gray-100 pt-6"><h3 className="text-lg font-bold text-slate-700 mb-4 flex items-center gap-2"><MapPin className="w-5 h-5"/> Adresse de livraison</h3><div className="grid gap-4"><label className="block"><span className="text-sm font-bold text-slate-700">Adresse (Numéro et rue)</span><input type="text" name="adresse" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 border" value={clientInfo.adresse} onChange={handleChange} placeholder="123 Rue Principale" /></label></div></div></div></div>);
};